language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t wychme/myfirstdocker -f Dockerfile.dev .

script:
  - docker run -e CI=true wychme/myfirstdocker npm run test

deploy: 
  privider: elasticbeanstalk
  region: "us-east-1"
  app: "MyFirstDocker"
  env: "Myfirstdocker-env"